var name = "Yaakov";
console.log("Hello " + name);
var name2 = "John";
console.log("Goodbye "+ name2);
var name3 = " Jen";
console.log("Goodbye "+name3);
var name4 = "Jason";
console.log("Goodbye "+name4);
var name5 = "Paul";
console.log("Hello "+name5);
var name6 = "Frank";
console.log("Hello "+name6);
var name7 = "Larry";
console.log("Hello "+name7);
var name8 = "Paula";
console.log("Hello "+name8);
var name9 = "Laura";
console.log("Hello "+name9);
var name10 = "Jim";
console.log("Goodbye "+name10)